version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bollinger-gang"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mgspf75b1fez"
s3_prefix = "bollinger-gang"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
