version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bollinger-gang"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-mqc7p2hdvd3x"
s3_prefix = "bollinger-gang"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
