AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bollinger-gang

  Sample SAM Template for bollinger-gang

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BollingerGangFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: check_bands/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        BollingerGang:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BollingerGangApi:
    Description: "API Gateway endpoint URL for Prod stage for BollingerGang function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BollingerGangFunction:
    Description: "BollingerGang Lambda Function ARN"
    Value: !GetAtt BollingerGangFunction.Arn
  BollingerGangFunctionIamRole:
    Description: "Implicit IAM Role created for BollingerGang function"
    Value: !GetAtt BollingerGangFunctionRole.Arn
